apiVersion: v1
kind: Namespace
metadata:
  name: aws-observability
  annotations:
    name: aws-observability
  labels:
    aws-observability: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  output.conf: |
    [OUTPUT]
        Name              cloudwatch
        Match             *
        region            us-east-1
        log_group_name    /aws/eks/your-project/cluster
        log_stream_prefix nodes-
        auto_create_group true
  parsers.conf: |
    [PARSER]
        Name   json
        Format json
